### ISSUE TITLE
How to get text with markdown tag from your library?

### ISSUE THREAD

**Issue by thaworn-li** [YahiaAngelo/MarkdownEditText#4]
Hi, I tested your library and it' great with simple kotlin code but I can't find the way to get raw markdown text. How can I do this?

**Comment by YahiaAngelo** [comment]
You can do that by using `getMD()` function in markdownEditText

**Comment by thaworn-li** [comment]
It doesn't work with Samsung devices. ex Note 9. Other devices is fine.

**Comment by YahiaAngelo** [comment]
Can you please share more info about the issue?
Like what happens when you call the `getMD()` function, And if you can share logs it'll be great.
