### ISSUE TITLE
How to store the text in the local database with 'Bold', 'Italics', 'bullets' etc... ?

### ISSUE THREAD

**Issue by dakshaavitech** [YahiaAngelo/MarkdownEditText#5]
I'm trying to get the text content from the MarkdownEditText by this :

`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                note.setNote(Html.toHtml(new SpannableString(Objects.requireNonNull(binding.editor).getText()), Html.TO_HTML_PARAGRAPH_LINES_INDIVIDUAL));
            } else {
                note.setNote(Html.toHtml(new SpannableString(Objects.requireNonNull(binding.editor).getText())));
            }`
            
            But it is not saving the text what we need to display in proper format like bold, italic etc...
            
            In database it is saved like below text :
            
            <p dir="ltr" style="margin-top:0; margin-bottom:0;">bold</p> <p dir="ltr" style="margin-top:0; margin-bottom:0;">italic</p> <p dir="ltr" style="margin-top:0; margin-bottom:0;"><span style="text-decoration:line-through;"><span style="text-decoration:line-through;">s</span></span><span style="text-decoration:line-through;">trike</span></p> 
            
            Can you please look into it?
            
            Thank you.

**Comment by YahiaAngelo** [comment]
MarkdownEditText is used to export/render styled string in Markdown format using `editor.getMD()` and `editor.renderMD()`.
And it looks like you want to save the styled string as HTML, which has nothing to do with this library.
So the code snippet you provided should work normally. I suggest you check the rest of your code.
