### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by vijayjvvc** [YahiaAngelo/MarkdownEditText#8]
![image](https://user-images.githubusercontent.com/67819608/186081331-4387ac47-76f5-4ddf-ba14-4acc7e97c951.png)
 text is not rendering properly.
How to solve this issue

code

 binding.idEdtNoteDesc.renderMD(it.body)

**Comment by TimurIsroilov123** [comment]
Have the same issue. Bold, italic and strike features are not working 
![editTextBug](https://user-images.githubusercontent.com/55947905/189971319-c5e53d3d-6192-4773-a6b4-acc2c667fb85.gif)

**Comment by raghunandankavi2010** [comment]
Same with me as well.

**Comment by Catnatsuki** [comment]
Any workarounds for this?
Adding to these: 
If a Link is added above any other form of markdown, the link and everything underneath it will not render.

https://user-images.githubusercontent.com/52190402/219608976-8b2e850e-a11a-4230-9b3f-3119a4723465.mp4

**Comment by udaynayak88** [comment]
Same with me as well. Any solution?
